version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: crash-game-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crash_game
      MYSQL_USER: crash_user
      MYSQL_PASSWORD: crash_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - crash-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: crash-game-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - crash-network

  # 游戏后端服务
  game-backend:
    build: .
    container_name: crash-game-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_MODE=release
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=crash_user
      - DATABASE_PASSWORD=crash_password
      - DATABASE_DATABASE=crash_game
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - JWT_SECRET=crash-game-secret-key-change-in-production
      - JWT_EXPIRE_TIME=24
    depends_on:
      - mysql
      - redis
    networks:
      - crash-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: crash-game-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - game-backend
    networks:
      - crash-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  crash-network:
    driver: bridge
