# 游戏后端服务配置文件

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # debug, release, test
  read_timeout: 30
  write_timeout: 30

# 数据库配置
database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "crash_game"
  charset: "utf8mb4"
  max_idle: 10
  max_open: 100

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

# JWT配置
jwt:
  secret: "crash-game-secret-key-change-in-production"
  expire_time: 24  # 小时
  issuer: "crash-game"

# 游戏配置
game:
  min_bet_amount: 1.0      # 最小下注金额
  max_bet_amount: 1000.0   # 最大下注金额
  min_multiplier: 1.01     # 最小倍数
  max_multiplier: 1000.0   # 最大倍数
  round_duration: 30       # 游戏轮次持续时间(秒)
  betting_duration: 15     # 下注阶段持续时间(秒)
  waiting_duration: 10     # 等待阶段持续时间(秒)
  update_interval: 100     # 状态更新间隔(毫秒)
  max_players_per_game: 1000 # 每局最大玩家数

# 日志配置
log:
  level: "info"      # debug, info, warn, error
  format: "json"    # json, text
  output: "stdout"  # stdout, file
  max_size: 100     # MB
  max_backups: 3
  max_age: 7        # days
